version: 2.1
orbs:
  android: circleci/android@0.2.1
commands:
  install-ndk: android/install-ndk
  restore-android-build-cache: android/restore-build-cache
  save-android-build-cache: android/save-build-cache
  restore-gradle-cache:
    description: "Restore gradle caches"
    steps:
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "Corona-Warn-App/build.gradle" }}-{{ checksum  "Server-Protocol-Buffer/build.gradle" }}
  save-gradle-cache:
    description: "Save gradle caches"
    steps:
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "Corona-Warn-App/build.gradle" }}-{{ checksum  "Server-Protocol-Buffer/build.gradle" }}
  require-version-bump:
    description: "Require version bump for binary assembling"
    steps:
      - run:
          name: "Check if assemble required"
          command: |
            last_commit=$(git log -1 --pretty=%B)
            if [[ $last_commit != *"Version bump"* ]]; then
              circleci-agent step halt
              echo "Skipping job"
            fi
  run-gradle-cmd:
    description: "Running gradle command with environment options"
    parameters:
      desc:
        type: string
        default: "Running gradle command"
      cmd:
        type: string
    steps:
      - run:
          name: << parameters.desc >>
          command: ./gradlew << parameters.cmd >>
          environment:
            JVM_OPTS: -Xmx2048m
            GRADLE_OPTS: -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
  run-gradle-cmd-test-splitting:
    description: "Running gradle command with environment options and test splitting"
    parameters:
      desc:
        type: string
        default: "Running gradle command"
      cmd:
        type: string
    steps:
      - run:
          name: Test splitting output
          command: circleci tests glob "**/test*/**/*.kt" | circleci tests split | xargs -n 1 echo
      - run:
          name: << parameters.desc >>
          command: ./gradlew << parameters.cmd >> -i -PtestFilter="`circleci tests glob "**/test*/**/*.kt" | circleci tests split`"
          environment:
            JVM_OPTS: -Xmx2048m
            GRADLE_OPTS: -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false

jobs:
  quick_build_device_release_no_tests:
    executor: android/android
    working_directory: ~/project
    steps:
      - checkout
      - restore-gradle-cache
      - restore-android-build-cache
      - require-version-bump
      - install-ndk:
          ndk-sha: "c81a5bcb4672a18d3647bf6898cd4dbcb978d0e8"
          ndk-version: "android-ndk-r21c"
      - run-gradle-cmd:
          desc: Quick Build
          cmd: "assembleDeviceSdkApiRelease"
      - save-gradle-cache
      - save-android-build-cache
      - store_artifacts:
          path: Corona-Warn-App/build/reports
          destination: reports
  quick_build_device_for_testers_release_no_tests:
    executor: android/android
    working_directory: ~/project
    steps:
      - checkout
      - restore-gradle-cache
      - restore-android-build-cache
      - require-version-bump
      - install-ndk:
          ndk-sha: "c81a5bcb4672a18d3647bf6898cd4dbcb978d0e8"
          ndk-version: "android-ndk-r21c"
      - run-gradle-cmd:
          desc: Quick Build
          cmd: ":Corona-Warn-App:assembleDeviceForTestersSdkApiRelease"
      - save-gradle-cache
      - save-android-build-cache
      - store_artifacts:
          path: Corona-Warn-App/build/reports
          destination: reports
  device_release_unit_tests:
    executor: android/android
    working_directory: ~/project
    parallelism: 3
    steps:
      - checkout
      - restore-gradle-cache
      - restore-android-build-cache
      - run-gradle-cmd-test-splitting:
          desc: Unit tests
          cmd: ":Corona-Warn-App:testDeviceSdkApiReleaseUnitTest -i"
      - save-gradle-cache
      - save-android-build-cache
      - store_artifacts:
          path: Corona-Warn-App/build/reports
          destination: reports
      - store_test_results:
          path: Corona-Warn-App/build/test-results
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - ./project
  device_for_testers_release_unit_tests:
    executor: android/android
    working_directory: ~/project
    parallelism: 3
    steps:
      - checkout
      - restore-gradle-cache
      - restore-android-build-cache
      - run-gradle-cmd-test-splitting:
          desc: Unit tests with splitting
          cmd: ":Corona-Warn-App:testDeviceForTestersSdkApiReleaseUnitTest"
      - save-gradle-cache
      - save-android-build-cache
      - store_artifacts:
          path: Corona-Warn-App/build/reports
          destination: reports
      - store_test_results:
          path: Corona-Warn-App/build/test-results
  lint_device_release_check:
    executor: android/android
    working_directory: ~/project
    steps:
      - checkout
      - restore-gradle-cache
      - restore-android-build-cache
      - run-gradle-cmd:
          desc: Lint check deviceRelease
          cmd: ":Corona-Warn-App:lintDeviceSdkApiRelease -i"
      - store_artifacts:
          path: Corona-Warn-App/build/reports
          destination: reports
  ktlint_device_release_check:
    executor: android/android
    working_directory: ~/project
    steps:
      - checkout
      - restore-gradle-cache
      - restore-android-build-cache
      - run-gradle-cmd:
          desc: Ktlint check deviceRelease
          cmd: ":Corona-Warn-App:ktlintDeviceSdkApiReleaseCheck"
      - store_artifacts:
          path: Corona-Warn-App/build/reports
          destination: reports
  lint_device_for_testers_release_check:
    executor: android/android
    working_directory: ~/project
    steps:
      - checkout
      - restore-gradle-cache
      - restore-android-build-cache
      - run-gradle-cmd:
          desc: Lint check deviceForTestersRelease
          cmd: ":Corona-Warn-App:lintDeviceForTestersSdkApiRelease -i"
      - store_artifacts:
          path: Corona-Warn-App/build/reports
          destination: reports
  ktlint_device_for_testers_release_check:
    executor: android/android
    working_directory: ~/project
    steps:
      - checkout
      - restore-gradle-cache
      - restore-android-build-cache
      - run-gradle-cmd:
          desc: Ktlint check deviceForTestersRelease
          cmd: ":Corona-Warn-App:ktlintDeviceForTestersSdkApiReleaseCheck"
      - store_artifacts:
          path: Corona-Warn-App/build/reports
          destination: reports
  detekt:
    executor: android/android
    working_directory: ~/project
    steps:
      - checkout
      - restore-gradle-cache
      - restore-android-build-cache
      - run-gradle-cmd:
          desc: Detekt check
          cmd: ":Corona-Warn-App:detekt"
      - store_artifacts:
          path: Corona-Warn-App/build/reports
          destination: reports
workflows:
  version: 2
  quick_build:
    jobs:
      - quick_build_device_release_no_tests
      - quick_build_device_for_testers_release_no_tests
      - device_release_unit_tests
      - device_for_testers_release_unit_tests
      - lint_device_release_check
      - lint_device_for_testers_release_check
      - ktlint_device_release_check
      - ktlint_device_for_testers_release_check
      - detekt
